import re


def camera_config_index(cam):
    """Return a numeric OpenCV camera index for config.yaml."""
    raw = cam.get("video_index", cam.get("index", 0))

    if isinstance(raw, int):
        return raw

    raw_text = str(raw)
    match = re.search(r"video(\d+)", raw_text)
    if match:
        return int(match.group(1))

    try:
        return int(raw_text)
    except Exception:
        return 0


def save_launcher_config(app, config_path):
    """Write config.yaml from the current launcher state."""
    speed = 100
    smoothing = 5
    precision = app.precision_var.get()
    gripper_trigger_mode = app.gripper_trigger_mode_var.get()

    if app.no_cameras_var.get():
        cameras_block = "cameras: {}\n"
        arm_cameras = "\n    cameras: []"
    else:
        cameras = app.detected_cameras or [
            {
                "name": "wrist",
                "index": 0,
                "width": 640,
                "height": 480,
                "fps": 30,
                "fourcc": "MJPG",
                "warmup_s": 15,
                "backend": "V4L2",
            }
        ]

        camera_lines = ["cameras:"]
        for cam in cameras:
            camera_lines.extend(
                [
                    f"  {cam['name']}:",
                    f"    index: {camera_config_index(cam)}",
                    f"    width: {cam.get('width', 640)}",
                    f"    height: {cam.get('height', 480)}",
                    f"    fps: {cam.get('fps', 30)}",
                    f"    fourcc: {cam.get('fourcc', 'MJPG')}",
                    f"    warmup_s: {cam.get('warmup_s', 15)}",
                    f"    backend: {cam.get('backend', 'V4L2')}",
                ]
            )

        cameras_block = "\n".join(camera_lines)
        camera_names = ", ".join(cam["name"] for cam in cameras)
        arm_cameras = f"\n    cameras: [{camera_names}]"

    arm_port = "dummy" if app.dummy_var.get() else app.detected_port

    yaml_content = f"""# Telerobot Configuration generated by the Launcher
robot:
  id: single_arm
  fps: 10
  use_rerun: false

{cameras_block}

arms:
  right:
    type: so100
    port: "{arm_port}"
    use_degrees: true{arm_cameras}
    regularization: 1.0e-3
    end_effector_step_sizes: {{ x: 0.8, y: 0.8, z: 0.8 }}
    end_effector_bounds:
      min: [-1.0, -1.0, -1.0]
      max: [1.0, 1.0, 1.0]
    max_ee_step_m: 0.20
    gripper_speed_factor: 20.0

teleop:
  speed: {speed}
  smoothing: {smoothing}
  precision_mode: "{precision}"
  gripper_trigger_mode: "{gripper_trigger_mode}"
"""

    if app.enable_dataset_var.get():
        yaml_content += f"""
dataset:
  repo_id: "{app.repo_var.get()}"
  push_to_hub: {str(app.push_hub_var.get()).lower()}
"""

    config_path.write_text(yaml_content, encoding="utf-8")
