import customtkinter as ctk
import subprocess
import os
import threading
import time
import re
import copy
from pathlib import Path
from camera_prompt import prompt_camera_assignment_window
from usb import ensure_usbipd_buses_shared, attach_usbipd_device_to_wsl, find_wsl_serial_port
from log_filters import should_hide_log_line
from camera_candidates import clean_camera_friendly_name, build_windows_camera_candidates
from config_writer import save_launcher_config, camera_config_index

# Paths
LAUNCHER_DIR = Path(__file__).resolve().parent
ROOT_DIR = LAUNCHER_DIR.parent
CONFIG_PATH = ROOT_DIR / "config.yaml"
RUNTIME_SETTINGS_PATH = ROOT_DIR / "runtime_settings.yaml"
RUNTIME_DIR = ROOT_DIR / "_runtime"
RUNTIME_DIR.mkdir(exist_ok=True)
WSL_VENV_PATH = os.environ.get("TELEROBOT_WSL_VENV", "~/telerobot-venv")

ctk.set_appearance_mode("Dark")
ctk.set_default_color_theme("blue")

class TelerobotLauncher(ctk.CTk):
    def __init__(self):
        super().__init__()
        self.title("Telerobot VR Control Center")
        self.geometry("750x900")
        self.server_process = None
        self.last_line_is_progress = False
        self.detected_port = "/dev/ttyACM0"
        self.detected_cameras = []
        self.runtime_dir = RUNTIME_DIR
        self.last_camera_buses = []
        self.wsl_keepalive_process = None

        self.protocol("WM_DELETE_WINDOW", self.on_closing)

        # --- TABS ---
        self.tabs = ctk.CTkTabview(self)
        self.tabs.pack(fill="both", expand=True, padx=20, pady=(20, 10))
        
        self.tab_control = self.tabs.add("Control Center")
        self.tab_training = self.tabs.add("Training Data")

        self.build_control_center()
        self.build_training_center()
        self.build_terminal()

    def is_usbipd_busid(self, value):
        """Return True only for real usbipd BUSIDs like '1-4' or '2-2'.

        usbipd list may also contain persisted device GUIDs. Those are not valid
        for --busid attach and must be ignored.
        """
        return isinstance(value, str) and re.match(r"^\d+-\d+$", value.strip()) is not None

    def abort_launch(self, message):
        """Abort server launch cleanly and restore launcher buttons."""
        self.stop_wsl_keepalive()
        self.log_to_terminal(message + "\n")
        self.btn_launch.configure(state="normal", text="LAUNCH SERVER")
        self.btn_estop.configure(state="disabled")
        self.server_process = None

    def camera_config_index(self, cam):
        """Return a numeric OpenCV camera index for config.yaml."""
        return camera_config_index(cam)

    def current_runtime_settings(self):
        """Return launcher-controlled live teleop settings."""
        return {
            "workspace_scale": self.precision_var.get(),
            "gripper_trigger_mode": self.gripper_trigger_mode_var.get(),
        }

    def write_runtime_settings(self, quiet=False):
        """Write runtime_settings.yaml for the running server to poll."""
        try:
            settings = self.current_runtime_settings()
            content = (
                "# Runtime teleop settings generated by launcher\n"
                f"workspace_scale: \"{settings['workspace_scale']}\"\n"
                f"gripper_trigger_mode: \"{settings['gripper_trigger_mode']}\"\n"
            )
            RUNTIME_SETTINGS_PATH.write_text(content, encoding="utf-8")

            if not quiet and self.server_process is not None:
                self.log_to_terminal(
                    f"⚙️ Runtime settings sent: {settings['workspace_scale']}, {settings['gripper_trigger_mode']}\n"
                )
        except Exception as e:
            self.log_to_terminal(f"⚠️ Failed to write runtime settings: {e}\n")

    def on_runtime_setting_changed(self, *_args):
        """Callback for dropdown changes."""
        self.write_runtime_settings(quiet=False)

    def save_config(self):
        """Write config.yaml from the current launcher state."""
        save_launcher_config(self, CONFIG_PATH)

    def build_control_center(self):
        self.top_wrap = ctk.CTkFrame(self.tab_control, fg_color="transparent")
        self.top_wrap.pack(fill="both", expand=True)

        toggles_frame = ctk.CTkFrame(self.top_wrap)
        toggles_frame.pack(fill="x", pady=10, padx=10)

        ctk.CTkLabel(
            toggles_frame,
            text="System Toggles",
            font=("Arial", 16, "bold")
        ).pack(anchor="w", padx=10, pady=(10, 5))

        self.dummy_var = ctk.BooleanVar(value=False)
        ctk.CTkCheckBox(
            toggles_frame,
            text="Dummy Mode (Test without physical Robot Arm)",
            variable=self.dummy_var
        ).pack(anchor="w", padx=10, pady=5)

        self.no_cameras_var = ctk.BooleanVar(value=False)
        ctk.CTkCheckBox(
            toggles_frame,
            text="No Cameras Mode (Disable physical cameras)",
            variable=self.no_cameras_var
        ).pack(anchor="w", padx=10, pady=(5, 5))

        self.mock_cameras_var = ctk.BooleanVar(value=False)

        self.debug_logs_var = ctk.BooleanVar(value=False)
        ctk.CTkCheckBox(
            toggles_frame,
            text="Debug Logs (Show detailed server/network output)",
            variable=self.debug_logs_var
        ).pack(anchor="w", padx=10, pady=(5, 10))

        # Control precision collapsible panel.
        self.show_motion = False
        self.btn_toggle_motion = ctk.CTkButton(
            self.top_wrap,
            text="⚙️ Show Control Precision Settings",
            fg_color="gray30",
            hover_color="gray40",
            command=self.toggle_motion
        )
        self.btn_toggle_motion.pack(fill="x", pady=(0, 10), padx=10)

        self.frame_motion = ctk.CTkFrame(self.top_wrap)

        row_prec = ctk.CTkFrame(self.frame_motion, fg_color="transparent")
        row_prec.pack(fill="x", padx=10, pady=10)

        ctk.CTkLabel(row_prec, text="Workspace Scale:").pack(side="left")

        self.precision_var = ctk.StringVar(value="1:1 (Normal)")
        ctk.CTkOptionMenu(
            row_prec,
            variable=self.precision_var,
            values=["1:1 (Normal)", "2:1 (Delicate)"],
            command=self.on_runtime_setting_changed,
        ).pack(side="left", padx=10)

        row_gripper = ctk.CTkFrame(self.frame_motion, fg_color="transparent")
        row_gripper.pack(fill="x", padx=10, pady=(0, 10))

        ctk.CTkLabel(row_gripper, text="Gripper Trigger Mode:").pack(side="left")

        self.gripper_trigger_mode_var = ctk.StringVar(value="Press Trigger to Close")
        ctk.CTkOptionMenu(
            row_gripper,
            variable=self.gripper_trigger_mode_var,
            values=["Press Trigger to Close", "Press Trigger to Open"],
            command=self.on_runtime_setting_changed,
        ).pack(side="left", padx=10)

        # Calibration collapsible panel.
        self.show_calibration = False
        self.btn_toggle_calibration = ctk.CTkButton(
            self.top_wrap,
            text="🛠️ Show Calibration Settings",
            fg_color="gray30",
            hover_color="gray40",
            command=self.toggle_calibration
        )
        self.btn_toggle_calibration.pack(fill="x", pady=(0, 10), padx=10)

        self.frame_calibration = ctk.CTkFrame(self.top_wrap)

        row_calibration = ctk.CTkFrame(self.frame_calibration, fg_color="transparent")
        row_calibration.pack(fill="x", padx=10, pady=10)

        ctk.CTkLabel(row_calibration, text="Calibration Action:").pack(side="left")

        self.calibration_menu = ctk.CTkOptionMenu(
            row_calibration,
            values=["Select action", "Delete Calibration", "Export Calibration", "Import Calibration"],
            command=self.handle_calibration_menu,
        )
        self.calibration_menu.set("Select action")
        self.calibration_menu.pack(side="left", padx=10)

        action_frame = ctk.CTkFrame(self.tab_control, fg_color="transparent")
        action_frame.pack(side="bottom", fill="x", pady=10)

        self.btn_launch = ctk.CTkButton(
            action_frame,
            text="LAUNCH SERVER",
            fg_color="green",
            hover_color="darkgreen",
            height=50,
            command=self.launch_server
        )
        self.btn_launch.pack(side="left", fill="x", expand=True, padx=5)

        self.btn_estop = ctk.CTkButton(
            action_frame,
            text="E-STOP",
            fg_color="red",
            hover_color="darkred",
            height=50,
            command=self.stop_server,
            state="disabled"
        )
        self.btn_estop.pack(side="right", fill="x", expand=True, padx=5)


    def toggle_motion(self):
        self.show_motion = not self.show_motion
        if self.show_motion:
            self.frame_motion.pack(fill="x", pady=0, padx=10)
            self.btn_toggle_motion.configure(text="⚙️ Hide Control Precision Settings")
        else:
            self.frame_motion.pack_forget()
            self.btn_toggle_motion.configure(text="⚙️ Show Control Precision Settings")

    def toggle_calibration(self):
        self.show_calibration = not self.show_calibration
        if self.show_calibration:
            self.frame_calibration.pack(fill="x", pady=0, padx=10)
            self.btn_toggle_calibration.configure(text="🛠️ Hide Calibration Settings")
        else:
            self.frame_calibration.pack_forget()
            self.btn_toggle_calibration.configure(text="🛠️ Show Calibration Settings")


    def build_training_center(self):
        self.enable_dataset_var = ctk.BooleanVar(value=False)
        ctk.CTkCheckBox(self.tab_training, text="Enable Dataset Recording", variable=self.enable_dataset_var).pack(pady=10, anchor="w", padx=10)

        frame_ds = ctk.CTkFrame(self.tab_training)
        frame_ds.pack(fill="x", pady=10, padx=10)

        ctk.CTkLabel(frame_ds, text="HuggingFace Repo ID:").pack(anchor="w", padx=10, pady=(10,0))
        self.repo_var = ctk.StringVar(value="my_org/telerobot_data")
        ctk.CTkEntry(frame_ds, textvariable=self.repo_var, width=300).pack(anchor="w", padx=10, pady=5)

        self.push_hub_var = ctk.BooleanVar(value=False)
        ctk.CTkCheckBox(frame_ds, text="Auto-Push to Hub on Stop", variable=self.push_hub_var).pack(anchor="w", padx=10, pady=10)

    def build_terminal(self):
        ctk.CTkLabel(self, text="System Log").pack(anchor="w", padx=20)
        self.terminal = ctk.CTkTextbox(self, height=350, font=("Consolas", 12))
        self.terminal.pack(fill="both", expand=True, padx=20, pady=(0, 20))
        self.log_to_terminal("System Ready.\n")

    def log_to_terminal(self, text):
        clean_text = text.strip("\r\n")
        if not clean_text:
            return

        debug_enabled = getattr(self, "debug_logs_var", None) is not None and self.debug_logs_var.get()

        if should_hide_log_line(clean_text, debug_enabled=debug_enabled):
            return

        is_progress = clean_text.startswith("⏱ Loop") or clean_text.startswith("Loop")

        if getattr(self, "last_line_is_progress", False) and is_progress:
            self.terminal.delete("end-2c linestart", "end-1c")
            self.terminal.insert("end", clean_text + "\n")
        else:
            self.terminal.insert("end", clean_text + "\n")

        self.last_line_is_progress = is_progress
        self.terminal.see("end")

    def read_process_output(self, process):
        for line in iter(process.stdout.readline, ''):
            if line:
                self.terminal.after(0, self.log_to_terminal, line)
        process.stdout.close()

    def ensure_usbipd_buses_shared(self, buses, label):
        """Ensure one or more USB devices are shared with usbipd."""
        ensure_usbipd_buses_shared(self, buses, label)

    def ensure_arm_bus_shared(self, arm_busid):
        """Ensure the robot arm USB serial adapter is shared with usbipd."""
        self.ensure_usbipd_buses_shared(arm_busid, "Arm")

    def ensure_camera_buses_shared(self, camera_buses):
        """Ensure selected camera devices are shared with usbipd."""
        self.ensure_usbipd_buses_shared(camera_buses, "Camera")

    def discover_wsl_cameras(self):
        """Discover usable V4L2 camera capture nodes inside WSL.

        Delegates OpenCV/V4L2 probing to tools/discover_wsl_cameras.py and
        converts its CAMERA lines into launcher camera config dictionaries.
        """
        camera_names = ["wrist", "workspace", "side", "overhead"]
        script_path = LAUNCHER_DIR / "discover_wsl_cameras.py"
        wsl_script_path = str(script_path).replace("\\", "/").replace("C:", "/mnt/c").replace("c:", "/mnt/c")

        try:
            res = subprocess.run(
                [
                    "wsl",
                    "--",
                    "bash",
                    "-lc",
                    f"source {WSL_VENV_PATH}/bin/activate && PY_SITE=$(python3 -c 'import site; print(site.getsitepackages()[0])') && export LD_LIBRARY_PATH=$PY_SITE/cmeel.prefix/lib:$LD_LIBRARY_PATH && python3 '{wsl_script_path}'",
                ],
                capture_output=True,
                text=True,
                timeout=35,
                creationflags=subprocess.CREATE_NO_WINDOW,
            )
        except Exception as e:
            self.log_to_terminal(f"⚠️ Camera discovery failed: {e}\n")
            return []

        cameras = []

        for line in (res.stdout or "").splitlines():
            if line.startswith("SKIP\t"):
                parts = line.split("\t")
                if len(parts) >= 4:
                    self.log_to_terminal(f"⚠️ Skipping {parts[1]} index {parts[2]}: {parts[3]}\n")
                continue

            if not line.startswith("CAMERA\t"):
                continue

            parts = line.split("\t")
            if len(parts) < 3:
                continue

            dev = parts[1]
            index = int(parts[2])
            usb_name = parts[3].strip() if len(parts) >= 4 else ""

            if len(cameras) >= len(camera_names):
                break

            name = camera_names[len(cameras)]

            cameras.append(
                {
                    "name": name,
                    "index": index,
                    "video_index": index,
                    "device": dev,
                    "usb_name": usb_name,
                    "width": 640,
                    "height": 480,
                    "fps": 30,
                    "fourcc": "MJPG",
                    "warmup_s": 15,
                    "backend": "V4L2",
                }
            )

        if cameras:
            self.log_to_terminal("✨ OpenCV-validated camera devices detected:\n")
            for cam in cameras:
                friendly = cam.get("usb_name") or f"index {cam['index']}"
                self.log_to_terminal(
                    f"   - {cam['name']}: {friendly} | {cam['device']} → index {cam['index']} "
                    f"(MJPG 640x480@30)\n"
                )
        else:
            self.log_to_terminal("❌ No OpenCV-usable MJPG cameras found in WSL.\n")

        return cameras

    def final_validate_selected_cameras(self):
        """Final OpenCV validation immediately before launching the server.

        Physical cameras are validated by tools/validate_wsl_cameras.py.
        Mock/no-camera modes skip validation.
        """
        if self.no_cameras_var.get() or not self.detected_cameras:
            return True

        import json

        camera_specs = []
        for cam in self.detected_cameras:
            camera_specs.append(
                {
                    "name": cam.get("name", "camera"),
                    "index": self.camera_config_index(cam),
                    "width": int(cam.get("width", 640)),
                    "height": int(cam.get("height", 480)),
                    "fps": int(cam.get("fps", 30)),
                    "fourcc": cam.get("fourcc", "MJPG"),
                }
            )

        specs_path = RUNTIME_DIR / "camera_specs.json"
        specs_path.write_text(json.dumps(camera_specs), encoding="utf-8")

        script_path = LAUNCHER_DIR / "validate_wsl_cameras.py"

        wsl_specs_path = str(specs_path).replace("\\", "/").replace("C:", "/mnt/c").replace("c:", "/mnt/c")
        wsl_script_path = str(script_path).replace("\\", "/").replace("C:", "/mnt/c").replace("c:", "/mnt/c")

        try:
            res = subprocess.run(
                [
                    "wsl",
                    "--",
                    "bash",
                    "-lc",
                    f"source {WSL_VENV_PATH}/bin/activate && PY_SITE=$(python3 -c 'import site; print(site.getsitepackages()[0])') && export LD_LIBRARY_PATH=$PY_SITE/cmeel.prefix/lib:$LD_LIBRARY_PATH && python3 '{wsl_script_path}' '{wsl_specs_path}'",
                ],
                capture_output=True,
                text=True,
                timeout=25,
                creationflags=subprocess.CREATE_NO_WINDOW,
            )
        except Exception as e:
            self.log_to_terminal(f"❌ Final camera validation failed to run: {e}\n")
            return False

        failed = []
        for line in (res.stdout or "").splitlines():
            if line.startswith("FAIL\t"):
                parts = line.split("\t")
                if len(parts) >= 3:
                    failed.append((parts[1], parts[2]))

        if res.returncode == 0 and not failed:
            return True

        if failed:
            self.log_to_terminal("❌ Camera validation failed just before launch:\n")
            for name, index in failed:
                self.log_to_terminal(f"   - {name}: OpenCV could not reopen index {index}\n")
        else:
            err = ((res.stdout or "") + "\n" + (res.stderr or "")).strip()
            self.log_to_terminal(f"❌ Camera validation failed just before launch: {err}\n")

        return False

    def clean_camera_friendly_name(self, name):
        """Clean duplicated/cluttered camera names from usbipd/V4L2 output."""
        return clean_camera_friendly_name(name)

    def build_windows_camera_candidates(self, usbipd_out):
        """Build camera candidate list from Windows usbipd output before WSL attach."""
        return build_windows_camera_candidates(usbipd_out, self.is_usbipd_busid)

    def prompt_camera_assignment_before_attach(self, camera_candidates):
        """Prompt for camera roles before cameras are attached to WSL."""
        pending_roles = prompt_camera_assignment_window(self, camera_candidates)

        self.pending_camera_roles = pending_roles
        self.camera_roles_prompted_before_attach = True

        self.log_to_terminal("✨ Camera role assignment selected. Cameras will attach after this step.\n")

    def apply_pending_roles_to_discovered_cameras(self):
        """Apply pre-attach role choices to OpenCV-discovered cameras by order."""
        pending = [
            item for item in list(getattr(self, "pending_camera_roles", []) or [])
            if item.get("role") != "disabled"
        ]
        if not pending or not self.detected_cameras:
            return

        assigned = []
        for i, cam in enumerate(self.detected_cameras[:len(pending)]):
            role = pending[i].get("role", "disabled")

            new_cam = copy.deepcopy(cam)
            new_cam["name"] = role

            # Preserve friendlier Windows-side name if available.
            if pending[i].get("usb_name"):
                new_cam["usb_name"] = self.clean_camera_friendly_name(pending[i]["usb_name"])
            elif new_cam.get("usb_name"):
                new_cam["usb_name"] = self.clean_camera_friendly_name(new_cam["usb_name"])

            assigned.append(new_cam)

        if assigned:
            self.detected_cameras = assigned
            self.log_to_terminal("✨ Camera role assignment applied:\n")
            for cam in self.detected_cameras:
                device = cam.get("usb_name", "index {}".format(cam.get("video_index", cam.get("index", "?"))))
                self.log_to_terminal(
                    "   - {}: {} → index {}\n".format(
                        cam["name"],
                        device,
                        cam.get("video_index", cam.get("index", "?")),
                    )
                )


    def stop_wsl_keepalive(self):
        """Stop the temporary WSL keepalive process if it is running."""
        proc = getattr(self, "wsl_keepalive_process", None)
        if proc is None:
            return

        try:
            if proc.poll() is None:
                proc.terminate()
        except Exception:
            pass

        self.wsl_keepalive_process = None

    def keep_wsl_alive_for_usbipd(self):
        """Keep WSL alive only during USB attach.

        This avoids a fixed timer. The launcher starts this temporary process
        after the camera role prompt and before usbipd attach. Once the real
        telerobot server process starts, stop_wsl_keepalive() is called and the
        server itself keeps WSL alive.
        """
        try:
            existing = getattr(self, "wsl_keepalive_process", None)
            if existing is not None and existing.poll() is None:
                return

            self.wsl_keepalive_process = subprocess.Popen(
                ["wsl", "--", "bash", "-lc", "sleep infinity"],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                creationflags=subprocess.CREATE_NO_WINDOW,
            )

            time.sleep(1.0)
        except Exception as e:
            self.log_to_terminal(f"⚠️ Warning keeping WSL alive: {e}\n")


    def attach_usbipd_device_to_wsl(self, busid, label, attempts=3):
        """Detach then attach one usbipd device to WSL with retries."""
        return attach_usbipd_device_to_wsl(self, busid, label, attempts=attempts)

    def find_wsl_serial_port(self, attempts=12, delay_s=1.0):
        """Find the first WSL serial port for the robot arm."""
        return find_wsl_serial_port(self, attempts=attempts, delay_s=delay_s)

    def get_enabled_camera_buses(self, usbipd_out):
        """Return camera BUSIDs that should be attached to WSL.

        If the pre-attach role prompt ran, this returns only cameras with
        non-disabled roles. Otherwise, it falls back to all Windows-detected
        camera candidates.
        """
        if getattr(self, "camera_roles_prompted_before_attach", False):
            return [
                item.get("busid")
                for item in getattr(self, "pending_camera_roles", [])
                if item.get("busid") and item.get("role") != "disabled"
            ]

        return [
            cam.get("busid")
            for cam in self.build_windows_camera_candidates(usbipd_out)
            if cam.get("busid")
        ]


    def begin_launch(self):
        """Prepare launcher UI/state for a new server launch."""
        self.detected_port = "/dev/ttyACM0"
        self.detected_cameras = []

        self.log_to_terminal("\n>> Starting Server...\n")
        self.warn_if_firewall_rules_missing()
        self.btn_launch.configure(state="disabled", text="RUNNING...")
        self.btn_estop.configure(state="normal")

    def scan_windows_usb_devices(self):
        """Return raw output from `usbipd list`."""
        self.log_to_terminal(">> Scanning Windows for USB Devices...\n")

        try:
            result = subprocess.run(
                ["usbipd", "list"],
                capture_output=True,
                text=True,
                creationflags=subprocess.CREATE_NO_WINDOW,
            )
            return result.stdout
        except Exception as e:
            self.log_to_terminal(f"⚠️ Error running usbipd: {e}\n")
            return ""

    def prepare_camera_role_selection(self, usbipd_out):
        """Prompt for camera roles before attaching cameras to WSL."""
        if self.no_cameras_var.get():
            return

        camera_candidates = self.build_windows_camera_candidates(usbipd_out)
        if not camera_candidates:
            return

        self.prompt_camera_assignment_before_attach(camera_candidates)
        self.last_camera_buses = [
            cam.get("busid")
            for cam in getattr(self, "pending_camera_roles", [])
            if cam.get("busid") and cam.get("role") != "disabled"
        ]

    def setup_robot_arm(self, usbipd_out):
        """Attach the robot arm to WSL and detect its serial port."""
        arm_ready = self.dummy_var.get()

        if self.dummy_var.get():
            self.log_to_terminal(">> Dummy Mode Active: Bypassing physical Arm connection.\n")
            return True

        self.log_to_terminal(">> Setting up Robot Arm...\n")

        try:
            arm_busid = None

            for line in usbipd_out.splitlines():
                if "1a86:55d3" in line or "CH34" in line:
                    parts = line.split()
                    if parts and self.is_usbipd_busid(parts[0]):
                        arm_busid = parts[0]
                        break

            if not arm_busid:
                self.log_to_terminal("⚠️ WARNING: No robot arm found via usbipd list.\n")
                return False

            self.ensure_arm_bus_shared(arm_busid)

            arm_attached_ok, attach_text = self.attach_usbipd_device_to_wsl(
                arm_busid,
                "Arm",
                attempts=3,
            )

            if not arm_attached_ok:
                short_attach_error = (attach_text.splitlines()[-1] if attach_text.splitlines() else attach_text).strip()
                self.log_to_terminal(f"⚠️ Failed to attach Arm BUSID {arm_busid}: {short_attach_error}\n")
                return False

            self.log_to_terminal(f"✨ Successfully attached Arm BUSID {arm_busid}!\n")

            port_match = self.find_wsl_serial_port()
            if not port_match:
                self.log_to_terminal("⚠️ Arm attached, but no ttyACM/ttyUSB serial port appeared.\n")
                return False

            self.detected_port = port_match
            self.log_to_terminal(f"✨ Auto-detected Arm Port: {self.detected_port}\n")
            arm_ready = True

        except Exception as e:
            self.log_to_terminal(f"⚠️ Error attaching Arm: {e}\n")
            return False

        return arm_ready

    def setup_physical_cameras(self, usbipd_out):
        """Attach selected cameras to WSL and discover OpenCV-usable devices."""
        if self.no_cameras_var.get():
            self.detected_cameras = []
            self.log_to_terminal(">> No Cameras Mode Active: Bypassing physical Camera connection.\n")
            return True

        self.log_to_terminal(">> Setting up Cameras...\n")

        try:
            camera_buses = self.get_enabled_camera_buses(usbipd_out)

            if not camera_buses:
                self.log_to_terminal("⚠️ WARNING: No cameras found via usbipd list.\n")
                return True

            selected_camera_buses = list(getattr(self, "last_camera_buses", []) or [])

            if getattr(self, "camera_roles_prompted_before_attach", False):
                camera_buses = [bus for bus in camera_buses if bus in selected_camera_buses]

            self.last_camera_buses = list(camera_buses)

            if not camera_buses:
                self.abort_launch(
                    "❌ No enabled cameras were selected. Server launch aborted. Enable at least one camera role."
                )
                return False

            self.ensure_camera_buses_shared(camera_buses)

            for bus in camera_buses:
                attached_ok, attach_text = self.attach_usbipd_device_to_wsl(
                    bus,
                    "Camera",
                    attempts=3,
                )

                if not attached_ok:
                    short_attach_error = (attach_text.splitlines()[-1] if attach_text.splitlines() else attach_text).strip()
                    self.log_to_terminal(f"⚠️ Failed to attach Camera BUSID {bus}: {short_attach_error}\n")

                    if self.debug_logs_var.get() and attach_text:
                        self.log_to_terminal(f"Debug attach output for Camera BUSID {bus}:\n{attach_text}\n")

            self.log_to_terminal(">> Pausing for 5 seconds to let webcam hardware fully initialize...\n")
            time.sleep(5)

            self.log_to_terminal(">> Unlocking Camera Permissions via Root...\n")
            subprocess.run(
                ["wsl", "-u", "root", "sh", "-c", "chmod 666 /dev/video*"],
                creationflags=subprocess.CREATE_NO_WINDOW,
            )

            self.detected_cameras = self.discover_wsl_cameras()

            if getattr(self, "camera_roles_prompted_before_attach", False):
                self.apply_pending_roles_to_discovered_cameras()

            if not self.detected_cameras:
                self.abort_launch(
                    "❌ Cameras were attached, but none could be opened by OpenCV in WSL. Server launch aborted. Try unplug/replug cameras or use No Cameras Mode."
                )
                return False

            self.log_to_terminal(">> Camera configured: OpenCV-validated MJPG + V4L2 + 640x480.\n")
            return True

        except Exception as e:
            self.log_to_terminal(f"⚠️ Error attaching Camera: {e}\n")
            return True

    def validate_cameras_before_launch(self):
        """Run final camera validation before starting the backend server."""
        if self.detected_cameras and not self.no_cameras_var.get():
            if not self.final_validate_selected_cameras():
                self.abort_launch(
                    "❌ Selected cameras could not be reopened before launch. Server launch aborted. Try launching again or use No Cameras Mode."
                )
                return False

        return True


    def wsl_project_path(self):
        """Return ROOT_DIR as a WSL /mnt/... path."""
        return str(ROOT_DIR).replace("\\", "/").replace("C:", "/mnt/c").replace("c:", "/mnt/c")

    def calibration_missing(self):
        """Return True when no usable LeRobot calibration JSON file exists."""
        if self.dummy_var.get():
            return False

        check_cmd = (
            "if find ~/.cache/huggingface/lerobot/calibration "
            "-type f -name '*.json' 2>/dev/null | head -1 | grep -q .; then "
            "echo CALIBRATION_OK; "
            "else echo NEEDS_CALIBRATION; fi"
        )

        try:
            res = subprocess.run(
                ["wsl", "--", "bash", "-lc", check_cmd],
                capture_output=True,
                text=True,
                timeout=10,
                creationflags=subprocess.CREATE_NO_WINDOW,
            )

            out = (res.stdout or "") + (res.stderr or "")
            return "NEEDS_CALIBRATION" in out

        except Exception as e:
            self.log_to_terminal(f"âš ï¸ Could not check robot calibration state: {e}\n")
            # Safer to require calibration than to let backend crash on input().
            return True

    def open_calibration_terminal(self):
        """Open an interactive terminal so LeRobot calibration input() can work."""
        RUNTIME_DIR.mkdir(exist_ok=True)

        wsl_path = self.wsl_project_path()
        bat_path = RUNTIME_DIR / "run_first_time_calibration.bat"

        bat_lines = [
            "@echo off",
            "title TeLeRobot First-Time Arm Calibration",
            "echo.",
            "echo ============================================================",
            "echo  TeLeRobot First-Time Arm Calibration",
            "echo ============================================================",
            "echo.",
            "echo Follow the instructions shown by LeRobot.",
            "echo Move the arm carefully when asked.",
            "echo Press ENTER in this window when LeRobot asks.",
            "echo.",
            "echo When calibration/server exits, WSL will be shut down automatically.",
            "echo Then close this window and click LAUNCH SERVER again.",
            "echo.",
            f"wsl -- bash -lc \"cd '{wsl_path}' && source {WSL_VENV_PATH}/bin/activate && PY_SITE=$(python3 -c 'import site; print(site.getsitepackages()[0])') && export LD_LIBRARY_PATH=$PY_SITE/cmeel.prefix/lib:$LD_LIBRARY_PATH && telerobot --config config.yaml --calibrate-only\"",
            "echo.",
            "echo Calibration command ended.",
            "echo Shutting down WSL to release USB devices and ports...",
            "wsl --shutdown",
            "echo.",
            "echo WSL shutdown complete.",
            "echo You may close this window and click LAUNCH SERVER again.",
        ]

        bat_path.write_text("\r\n".join(bat_lines) + "\r\n", encoding="ascii", errors="replace")

        subprocess.Popen(
            ["cmd.exe", "/c", str(bat_path)],
            creationflags=subprocess.CREATE_NEW_CONSOLE,
        )

    def handle_first_time_calibration_if_needed(self):
        """Launch interactive calibration if needed. Return True if normal launch should stop."""
        if not self.calibration_missing():
            return False

        self.log_to_terminal(
            "\n⚠️ First-time robot calibration is required.\n"
            "   A calibration terminal window will open.\n"
            "   Follow the instructions there.\n"
            "   After it finishes, WSL will shut down automatically.\n"
            "   Then click LAUNCH SERVER again.\n"
        )

        self.open_calibration_terminal()
        self.abort_launch(
            "⚠️ Calibration required. Complete calibration in the opened terminal, then launch again."
        )
        return True



    def firewall_rule_exists(self, rule_name):
        """Return True if a Windows firewall rule exists."""
        try:
            res = subprocess.run(
                [
                    "powershell",
                    "-NoProfile",
                    "-Command",
                    f"Get-NetFirewallRule -DisplayName '{rule_name}' -ErrorAction SilentlyContinue",
                ],
                capture_output=True,
                text=True,
                timeout=5,
                creationflags=subprocess.CREATE_NO_WINDOW,
            )
            return bool((res.stdout or "").strip())
        except Exception:
            return False

    def warn_if_firewall_rules_missing(self):
        """Warn if required TeLeRobot firewall rules are missing."""
        missing = []
        for rule_name, port in [("TeLeRobot 8765", 8765), ("TeLeRobot 8080", 8080)]:
            if not self.firewall_rule_exists(rule_name):
                missing.append(str(port))

        if missing:
            self.log_to_terminal(
                "⚠️ Windows firewall rule missing for port(s): "
                + ", ".join(missing)
                + ". Run Setup_TeLeRobot.bat again or add the firewall rules manually.\n"
            )

    def handle_calibration_menu(self, selection):
        """Handle calibration dropdown selection."""
        if selection == "Delete Calibration":
            self.delete_calibration_files()
        elif selection == "Export Calibration":
            self.export_calibration_files()
        elif selection == "Import Calibration":
            self.import_calibration_files()

        if hasattr(self, "calibration_menu"):
            self.calibration_menu.set("Select action")


    def delete_calibration_files(self):
        """Delete LeRobot calibration files so calibration can be rerun."""
        from tkinter import messagebox

        if self.server_process is not None:
            messagebox.showwarning(
                "Server running",
                "Stop the server with E-STOP before deleting calibration files.",
            )
            return

        confirmed = messagebox.askyesno(
            "Delete calibration?",
            "Delete existing LeRobot robot calibration files?\n\n"
            "The next launch will require first-time calibration again.",
        )

        if not confirmed:
            return

        try:
            res = subprocess.run(
                [
                    "wsl",
                    "--",
                    "bash",
                    "-lc",
                    "rm -rf ~/.cache/huggingface/lerobot/calibration && "
                    "mkdir -p ~/.cache/huggingface/lerobot/calibration && "
                    "echo CALIBRATION_DELETED",
                ],
                capture_output=True,
                text=True,
                timeout=15,
                creationflags=subprocess.CREATE_NO_WINDOW,
            )

            output = ((res.stdout or "") + "\n" + (res.stderr or "")).strip()

            if res.returncode == 0 and "CALIBRATION_DELETED" in output:
                self.log_to_terminal("✅ Calibration files deleted. WSL will shut down now.\n")
                subprocess.run(["wsl", "--shutdown"], creationflags=subprocess.CREATE_NO_WINDOW)
                self.log_to_terminal("✅ WSL shutdown complete. Next launch will trigger calibration.\n")
            else:
                self.log_to_terminal(f"❌ Failed to delete calibration files: {output}\n")

        except Exception as e:
            self.log_to_terminal(f"❌ Failed to delete calibration files: {e}\n")

    def export_calibration_files(self):
        """Export LeRobot calibration folder to the Windows Desktop."""
        from tkinter import messagebox

        try:
            desktop_win = Path.home() / "Desktop"
            export_win = desktop_win / "telerobot_calibration_backup"
            export_wsl = self.windows_path_to_wsl_path(export_win)

            cmd = (
                f"rm -rf '{export_wsl}' && "
                "if [ -d ~/.cache/huggingface/lerobot/calibration ] && "
                "[ -n \"$(find ~/.cache/huggingface/lerobot/calibration -type f 2>/dev/null | head -1)\" ]; then "
                f"cp -r ~/.cache/huggingface/lerobot/calibration '{export_wsl}' && "
                "echo CALIBRATION_EXPORTED; "
                "else echo NO_CALIBRATION; fi"
            )

            res = subprocess.run(
                ["wsl", "--", "bash", "-lc", cmd],
                capture_output=True,
                text=True,
                timeout=20,
                creationflags=subprocess.CREATE_NO_WINDOW,
            )

            output = ((res.stdout or "") + "\n" + (res.stderr or "")).strip()

            if "CALIBRATION_EXPORTED" in output:
                messagebox.showinfo(
                    "Export complete",
                    f"Calibration exported to Desktop:\n{export_win}",
                )
                self.log_to_terminal("âœ… Calibration exported to Desktop.\n")
            elif "NO_CALIBRATION" in output:
                messagebox.showwarning(
                    "No calibration found",
                    "No calibration files were found to export.",
                )
                self.log_to_terminal("âš ï¸ No calibration files found to export.\n")
            else:
                messagebox.showerror("Export failed", output or "Unknown export error.")
                self.log_to_terminal(f"âŒ Calibration export failed: {output}\n")

        except Exception as e:
            messagebox.showerror("Export failed", str(e))
            self.log_to_terminal(f"âŒ Calibration export failed: {e}\n")

    def import_calibration_files(self):
        """Import a calibration folder from Windows into WSL."""
        from tkinter import filedialog, messagebox

        if self.server_process is not None:
            messagebox.showwarning(
                "Server running",
                "Stop the server with E-STOP before importing calibration files.",
            )
            return

        selected = filedialog.askdirectory(
            title="Select calibration folder or telerobot_calibration_backup folder"
        )

        if not selected:
            return

        selected_path = Path(selected)

        # Accept either:
        #   Desktop/telerobot_calibration_backup
        # or:
        #   Desktop/telerobot_calibration_backup/calibration
        if selected_path.name.lower() == "calibration":
            source_wsl = self.windows_path_to_wsl_path(selected_path)
        elif (selected_path / "robots").exists():
            source_wsl = self.windows_path_to_wsl_path(selected_path)
        elif (selected_path / "calibration").exists():
            source_wsl = self.windows_path_to_wsl_path(selected_path / "calibration")
        else:
            messagebox.showerror(
                "Invalid folder",
                "Selected folder does not look like a LeRobot calibration folder.",
            )
            return

        try:
            cmd = (
                "mkdir -p ~/.cache/huggingface/lerobot && "
                "rm -rf ~/.cache/huggingface/lerobot/calibration && "
                f"cp -r '{source_wsl}' ~/.cache/huggingface/lerobot/calibration && "
                "echo CALIBRATION_IMPORTED"
            )

            res = subprocess.run(
                ["wsl", "--", "bash", "-lc", cmd],
                capture_output=True,
                text=True,
                timeout=20,
                creationflags=subprocess.CREATE_NO_WINDOW,
            )

            output = ((res.stdout or "") + "\n" + (res.stderr or "")).strip()

            if res.returncode == 0 and "CALIBRATION_IMPORTED" in output:
                messagebox.showinfo("Import complete", "Calibration imported successfully.")
                self.log_to_terminal("✅ Calibration imported successfully. WSL will shut down now.\n")
                subprocess.run(["wsl", "--shutdown"], creationflags=subprocess.CREATE_NO_WINDOW)
                self.log_to_terminal("✅ WSL shutdown complete.\n")
            else:
                messagebox.showerror("Import failed", output or "Unknown import error.")
                self.log_to_terminal(f"❌ Calibration import failed: {output}\n")

        except Exception as e:
            messagebox.showerror("Import failed", str(e))
            self.log_to_terminal(f"❌ Calibration import failed: {e}\n")


    def start_backend_server(self):
        """Start the WSL telerobot backend process."""
        wsl_path = str(ROOT_DIR).replace("\\", "/").replace("C:", "/mnt/c").replace("c:", "/mnt/c")
        dummy_flag = "--dummy" if self.dummy_var.get() else ""
        debug_flag = "1" if self.debug_logs_var.get() else "0"
        mock_camera_flag = "1" if self.no_cameras_var.get() else "0"

        cmd = (
            f"wsl -- bash -c \"cd '{wsl_path}' && export PYTHONUNBUFFERED=1 && "
            f"export TELEROBOT_DEBUG={debug_flag} && export TELEROBOT_MOCK_CAMERAS={mock_camera_flag} && "
            f"source {WSL_VENV_PATH}/bin/activate && PY_SITE=$(python3 -c 'import site; print(site.getsitepackages()[0])') && export LD_LIBRARY_PATH=$PY_SITE/cmeel.prefix/lib:$LD_LIBRARY_PATH && "
            f"export TELEROBOT_PORT={self.detected_port} && "
            f"telerobot {dummy_flag}\""
        )

        self.server_process = subprocess.Popen(
            cmd,
            shell=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            encoding="utf-8",
            errors="replace",
            bufsize=1,
            creationflags=subprocess.CREATE_NO_WINDOW,
        )

        # The real server process now keeps WSL alive; stop the temporary USB attach keepalive.
        self.stop_wsl_keepalive()

        threading.Thread(target=self.read_process_output, args=(self.server_process,), daemon=True).start()

    def launch_server(self):
        self.begin_launch()

        usbipd_out = self.scan_windows_usb_devices()
        self.prepare_camera_role_selection(usbipd_out)

        # Start WSL after camera role selection and keep it alive during USB attach.
        self.keep_wsl_alive_for_usbipd()

        if not self.setup_robot_arm(usbipd_out):
            self.abort_launch(
                "❌ Robot arm was not attached or no ttyACM/ttyUSB port was detected. Server launch aborted."
            )
            return

        if not self.setup_physical_cameras(usbipd_out):
            return

        if not self.validate_cameras_before_launch():
            return

        if not self.no_cameras_var.get() and not self.detected_cameras:
            self.abort_launch(
                "âŒ No usable camera was detected. Connect a camera and try again, or enable No Cameras Mode if you want to run without cameras."
            )
            return

        self.write_runtime_settings(quiet=True)
        self.save_config()

        if self.handle_first_time_calibration_if_needed():
            return

        self.start_backend_server()

    def stop_server(self):
        self.log_to_terminal("\n>> [E-STOP] INSTANTLY KILLING SERVER...\n")
        self.stop_wsl_keepalive()
        if self.server_process:
            self.server_process.kill()
            self.server_process = None
            
        subprocess.Popen("wsl -- bash -c \"pkill -9 -f telerobot || pkill -9 python3\"", shell=True, creationflags=subprocess.CREATE_NO_WINDOW)
        
        self.btn_estop.configure(state="disabled")
        self.btn_launch.configure(state="disabled", text="SHUTTING DOWN WSL...")
        self.log_to_terminal(">> Server killed. Waiting for WSL to safely shut down to release ports...\n")

        def background_shutdown():
            try:
                subprocess.run(["wsl", "--shutdown"], creationflags=subprocess.CREATE_NO_WINDOW)
            except:
                pass
            
            def reset_gui():
                self.btn_launch.configure(state="normal", text="LAUNCH SERVER")
                self.log_to_terminal(">> WSL shutdown complete. Ports are released and ready for restart.\n")
                
            self.after(0, reset_gui)
                
        threading.Thread(target=background_shutdown, daemon=True).start()

    def on_closing(self):
        subprocess.Popen(["wsl", "--shutdown"], creationflags=subprocess.CREATE_NO_WINDOW)
        self.destroy()

if __name__ == "__main__":
    app = TelerobotLauncher()
    app.mainloop()



